### ISSUE TITLE
What's the deal with this repo???

### ISSUE THREAD

**Issue by bezark** [dainsaint/spaceopera#1]
OMG it's happening. We're using github.

What sort of stuff do you think would be appropriate to include in this repo? I have several godot projects including dice cam stuff, experiments in visualizing storylets and resource tracking which i could move in here if it would seem useful. Relatedly, how would you feel about starting the architecture conversation literally here in issues and examples? Seems like a nice way to begin iterating on stuff.

**Comment by dainsaint** [comment]
Oh dang i missed this! I think this repo is great for little experiments etc, but for the actual datapad i created a separate repo (https://github.com/dainsaint/datapad) because I think at some point we're gonna wanna leverage github actions to deploy things and i dont want any weird conflicts? But maybe im overthinking it haha
